### ISSUE TITLE
Project build error: Non-resolvable parent POM.

### ISSUE THREAD

**Issue by mhabsaoui** [lappsgrid-services/edu.brandeis.cs.uima.dkpro#1]
Hello,

when trying to build this project's WAR from source, i get this project build error (under Eclipse):

```
Project build error: Non-resolvable parent POM for edu.brandeis.cs:uima.dkpro:0.0.1-SNAPSHOT: Failure to transfer org.lappsgrid.maven:parent-pom:pom:2.0.0 from http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local/ was cached in the local repository, resolution will not be reattempted until the update interval of dkpro has elapsed or updates are forced. Original error: Could not transfer artifact org.lappsgrid.maven:parent-pom:pom:2.0.0 from/to dkpro (http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local/): connect timed out and 'parent.relativePath' points at wrong local POM
```

What is wrong ?  

=> Last Eclipse Neon + maven
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.8.0-46-generic", arch: "amd64", family: "unix"

PS: 
- i've checked the maven repository artifact is OK : 
http://mvnrepository.com/artifact/org.lappsgrid.maven/war-parent-pom/2.0.5
-i've added this dependency directly to the pom
- I've tried to link this maven projet to the war-parent-pom one under Eclipse
- i've tried to add a settings.xml
- i've tried to remove/add maven nature

... , but all the same :/ 

![capture](https://cloud.githubusercontent.com/assets/18755135/25619324/bc363782-2f4a-11e7-8b0a-86e6c261d26f.PNG)

Thanks for Help 👍

**Comment by mhabsaoui** [comment]
As for start, it had to do with the internal nexus maven repository (accessed through proxy) which acces remote official maven repo in case artifact not found locally => a settings.xml had to be added to set the nexus repo / proxy config...

So mvn clean compile package doesn't succed thoug because of jars not existing :(   :

`The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1`

Thanks for help for those artifacts.

**Comment by reckart** [comment]
@mhabsaoui these artifacts are in the following repo

```
<repositories>
  <repository>
    <id>ukp-oss-model-releases</id>
    <url>http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local</url>
   </repository>
</repositories>
```

Cf. [DKPro Core - Setting up Maven repository](https://dkpro.github.io/dkpro-core/pages/setup-maven/)

**Comment by mhabsaoui** [comment]
Thanks for the answer.

i've already tried to addthis repo too, but kept having same errors at compile: 

`[ERROR] Failed to execute goal on project uima.dkpro: Could not resolve dependencies for project edu.brandeis.cs:uima.dkpro:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1`

**Comment by reckart** [comment]
If you use a catch-all proxy in your settings.xml then you need to make an exception for this repo.

By default, Maven caches info whether artifacts were not found and doesn't retry for a certain period. Did you try adding the "-U" parameter to your Maven call to force SNAPSHOT updates - or clear our your local ~/.m2/repository.

**Comment by mhabsaoui** [comment]
local ~/.m2/repository cleared out and command tested " mvn -U clean package" ==> still same result

`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.726 s
[INFO] Finished at: 2017-05-03T14:44:51+02:00
[INFO] Final Memory: 13M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project uima.dkpro: Could not resolve dependencies for project edu.brandeis.cs:uima.dkpro:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1: Failure to find org.lappsgrid:service-grid-libs:jar:1.1.0 in http://*****************/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project uima.dkpro: Could not resolve dependencies for project edu.brandeis.cs:uima.dkpro:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1: Failure to find org.lappsgrid:service-grid-libs:jar:1.1.0 in http://*************:****/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project edu.brandeis.cs:uima.dkpro:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1: Failure to find org.lappsgrid:service-grid-libs:jar:1.1.0 in *****************/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:212)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1: Failure to find org.lappsgrid:service-grid-libs:jar:1.1.0 in *********************/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1: Failure to find org.lappsgrid:service-grid-libs:jar:1.1.0 in *****************/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.lappsgrid:service-grid-libs:jar:1.1.0 in *************************/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`



PS: 
- Are there any already updated compiled WAR of lapps wrapped services for :  dkpro, gate,... ?

- Is-it possible you update the github repositories of services projects so they work without touching anything (versions of lapps.* in pom,...) ?

- Is there any updated wrapping tutorial (cause the one existing has old java api) ?

**Comment by reckart** [comment]
Your Maven seems to be configured to only look for artifacts in `http://*****************/repository/maven-public/` - could that be? It doesn't seem to consider the additional repositories.

**Comment by mhabsaoui** [comment]
I can confirm from the settings.xml, that those repos are also allowed : 
/repository/maven-releases/
/repository/maven-public/
/repository/maven-snapshots/

I've also even tried to add the "Configuring Maven for full access to the UKP Maven Repository" (<profile>, <activeProfile>), but in vain :/

PS: can i have your opinion on the extra questions, thanks in advance :+1:

**Comment by reckart** [comment]
These repos that you mention seem all to be repos of some server that you are using at your site. If that server doesn't look up artifacts in the repo that I mentioned [above](https://github.com/lappsgrid-services/edu.brandeis.cs.uima.dkpro/issues/1#issuecomment-298870960), you won't get the model artifacts.

I am using a catch-all proxy in my Maven settings.xml, but I have configured exceptions to also be able to access some other repos directly (i.e. circumventing the proxy):

```
        <mirrors>
                <mirror>
                        <id>internal-repo-proxy</id>
                        <mirrorOf>*,!ukp-oss-model-releases</mirrorOf>
                        <url>https://XXXXX/internal-grid</url>
                </mirror>
        </mirrors>
```

No idea how your settings.xml looks like.

**Comment by reckart** [comment]
The extra questions would be best answered by one of the LAPPS developers. I'm actually from DKPro Core ;)

**Comment by mhabsaoui** [comment]
In the settings.xml, i have (about mirrors...) :

`	<mirrors>
		<mirror>
			<id>central</id>
			<mirrorOf>*,!snapshots,!releases</mirrorOf>
			
			<url>http://****************************/repository/maven-public/</url>
		</mirror>
	</mirrors>

						<mirrors>
							<mirror>
								<id>central</id>
								<mirrorOf>*,!snapshots,!releases</mirrorOf>
								
								<url>http://***************************/repository/maven-public/</url>
							</mirror>
						</mirrors>
`
I'll add yours so to catch ones from ukp

**Comment by reckart** [comment]
Ah... looks like the ID used in this project differs from the one that we recommend:

```
 <repositories>
        <repository>
            <id>dkpro</id>
            <url>http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local/</url>
        </repository>
    </repositories>
```

So instead of 

```
<mirrorOf>*,!ukp-oss-model-releases</mirrorOf> 
```

try

```
<mirrorOf>*,!dkpro</mirrorOf> 
```

**Comment by mhabsaoui** [comment]
Arrrf, did not change :/

Is it ok when i run "mvn -U clean compile package" (i mean it includes the clearing of .m2/repository) ?

Here the output: 

`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.470 s
[INFO] Finished at: 2017-05-03T16:30:39+02:00
[INFO] Final Memory: 14M/189M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project uima.dkpro: Could not resolve dependencies for project edu.brandeis.cs:uima.dkpro:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.lappsgrid:service-grid-libs:jar:1.1.0, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-tagger-en-maxent:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-parser-en-chunking:jar:20120616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.opennlp-model-ner-en-person:jar:20130624.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-tagger-en-bidirectional-distsim:jar:20140616.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-parser-en-rnn:jar:20140104.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-ner-en-all.3class.distsim.crf:jar:20140827.1, de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.stanfordnlp-model-coref-en-default:jar:20140827.1`

**Comment by reckart** [comment]
"-U" doesn't clean the repo, but it is meant to tell Maven to ignore any cached info about the non-availablility of artifacts. You know... you can probably fix this simply by deleting your settings.xml (make sure you still have a copy of it... there's probably a reason why you are normally using it). If that works, then you should get in touch with a local Maven guru and get help fixing your settings.xml.

**Comment by mhabsaoui** [comment]
In fact, as we have to work on IDE environment behind a proxy, the build succeeded only when i added a User settings.xml (so without it didn't go well ^^)

Now, what i don't get, if those missing jars are reachable from dkpro maven repo, why Eclipse doesn't find them with the ukp-oss-model-releases repository...

i'll try to remove the User settings.xml, and i'll try on my personnal PC. And i'll let you hnow what ;)

Thanks a lot again, don't go far because i'll probably switch on the dkpro forum for other matters, and if you can tell someone from Lapps about my extra questions, please do :1st_place_medal: 

Thanks.

**Comment by mhabsaoui** [comment]
Well, on my personal PC i've tried the build (without settings.xml) and there is no more dkpro artifacts problems :)

Now, as on image only one artifact is missing to be able to finally build the projects (dkpro, gate)  :

![capture](https://cloud.githubusercontent.com/assets/18755135/25676811/c083d9a8-3043-11e7-8cc9-4cc5bca01281.PNG)
